CREATE TABLE animais(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    ESPECIE VARCHAR(30) NOT NULL,
    SEXO VARCHAR(30) NOT NULL,
    IDADE INT NOT NULL,
    LOCALIZACAO VARCHAR(50) NOT NULL
);

 CREATE TABLE gerente(
        ID INT PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(50) NOT NULL
    );

    CREATE TABLE cuidador(
        ID INT PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(50) NOT NULL,
        GERENTE_ID INT NOT NULL,
        FOREIGN KEY (GERENTE_ID) REFERENCES gerente (ID)
    );

    CREATE TABLE animal_cuidador(
        ANIMAL_ID INT,
        CUIDADOR_ID INT,
        CONSTRAINT PRIMARY KEY(ANIMAL_ID, CUIDADOR_ID),
        FOREIGN KEY (ANIMAL_ID) REFERENCES animais (ID),
        FOREIGN KEY (CUIDADOR_ID) REFERENCES cuidador (ID)
    );